{% set name = "msnoise" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc94e23d6f022c7e41fadc2acdfd585cee2853bfb2edf1897e5a875bbfb955ac

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - msnoise = msnoise.scripts.msnoise:run

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - numpy
    - scipy
    - pandas
    - matplotlib-base
    - sqlalchemy
    - obspy
    - click
    - pymysql
    - flask
    - flask-admin
    - flask-wtf
    - markdown
    - folium
    - wtforms
    - jinja2
    - scandir
    - logbook

test:
  imports:
    - msnoise
    - msnoise.test

about:
  home: http://github.com/ROBelgium/MSNoise
  license: EUPL-1.1
  license_family: OTHER
  license_file: LICENCE.txt
  summary: A Python Package for Monitoring Seismic Velocity Changes using Ambient Seismic Noise
  doc_url: http://msnoise.org/doc/
  dev_url: http://github.com/ROBelgium/MSNoise

extra:
  recipe-maintainers:
    - ThomasLecocq
